{% set name = "argo-workflows-dsl" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b9238c964776aae0c6b3b60045ce8e2fd14d380f7ea114bd2c29dc71b78ecc6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - argo-workflows >=2.1.4
    - inflection
    - python
    - pyyaml

test:
  imports:
    - argo.workflows.client
    - argo.workflows.client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/argo-workflows-dsl/
  summary: DSL for Argo Workflows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
